title: Kareem Haggag
description: Assistant Professor at the UCLA Anderson School of Management
sourcecode: "https://github.com/kareemhaggag/kareemhaggag.github.io"

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: "http://kareemhaggag.github.io"     # the base hostname & protocol for your site
baseurl: ""                   # the subpath of your site, e.g. /blog

author:
    name:
    facebook:
    scholar:

# Build settings
markdown: kramdown
highlighter: rouge

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#
analytics:
    provider: statcounter
    statcounter:
        sc_project  : 12670042
        sc_security : "bbe4f3a0"
        sc_invisible: 1
        sc_text     : 2
    google:
        tracking_id: 'UA-30569764-1'
    getclicky:
      site_id:
    mixpanel:
        token: ''
    piwik:
        baseURL: '' # Piwik installation address (without protocol)
        idsite: ''  # the id of the site on Piwik

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments:
    provider:
    disqus:
      short_name:
    livefyre:
      site_id:
    intensedebate:
      account:
    facebook:
      appid:
      num_posts: 5
      width: 580
      colorscheme: light

gems:
 - jekyll-seo-tag
